namespace DeanFernandes.Dota2UltOverlay.Models
{
    class Ultimate
    {
        public string Name { get; set; }
        public string UltImagePath { get; set; }
        public int CooldownDurationSeconds { get; set; }
        
        private static readonly Dictionary<string, int> _cooldowns = new Dictionary<string, int>
        {
            { "borrowed_time", 90 },
            { "dark_portal", 110 },
            { "chemical_rage", 60 },
            { "ice_blast", 60 },
            { "mana_void", 70 },
            { "tempest_double", 100 },
            { "culling_blade", 100 },
            { "nightmare", 120 },
            { "flaming_lasso", 90 },
            { "primal_roar", 90 },
            { "rupture", 75 },
            { "hunter_track", 6 },
            { "primal_split", 140 },
            { "warpath", 45 },
            { "insatiable_hunger", 45 },
            { "stampede", 100 },
            { "phantasm", 75 },
            { "hand_of_god", 150 },
            { "wind_walk", 24 },
            { "freezing_field", 100 },
            { "wall_of_replica", 100 },
            { "terrorize", 100 },
            { "solar_guardian", 120 },
            { "bad_juju", 3 },
            { "exorcism", 150 },
            { "static_storm", 90 },
            { "doom", 70 },
            { "elder_dragon_form", 100 },
            { "marksmanship", 0 },
            { "magnetize", 100 },
            { "echo_slam", 130 },
            { "earth_splitter", 100 },
            { "activate_fire_remnant", 0 },
            { "untouchable", 0 },
            { "black_hole", 180 },
            { "chronosphere", 160 },
            { "wrath_of_nature", 85 },
            { "soul_chain", 70 },
            { "call_down", 90 },
            { "sharpshooter", 45 },
            { "life_break", 16 },
            { "invoke", 7 },
            { "macropyre", 90 },
            { "omni_slash", 120 },
            { "spirit_form", 85 },
            { "ghostship", 90 },
            { "commander_duel", 60 },
            { "pulse_nova", 1 },
            { "chain_frost", 100 },
            { "infest", 80 },
            { "laguna_blade", 70 },
            { "finger_of_death", 140 },
            { "true_form", 100 },
            { "eclipse", 110 },
            { "shapeshift", 110 },
            { "reverse_polarity", 120 },
            { "unleash", 90 },
            { "arena_of_blood", 100 },
            { "stone_gaze", 90 },
            { "divided_we_stand", 0 },
            { "invis", 140 },
            { "wukongs_command", 100 },
            { "replicate", 140 },
            { "pierece_the_veil", 75 },
            { "song_of_the_siren", 180 },
            { "reapers_scythe", 100 },
            { "requieum", 120 },
            { "darkness", 140 },
            { "vendetta", 80 },
            { "sanity_eclipse", 150 },
            { "dumb_lock", 0 },
            { "guardian_angel", 110 },
            { "promise", 110 },
            { "gyroshell", 90 },
            { "coup_de_grace", 0 },
            { "juxtapose", 15 },
            { "supernova", 120 },
            { "pulverize", 40 },
            { "dream_coil", 75 },
            { "dismember", 30 },
            { "life_drain", 7 },
            { "sonic_wave", 110 },
            { "hookshot", 60 },
            { "eye_of_storm", 80 },
            { "backstab", 0 },
            { "spell_steal", 16 },
            { "epicenter", 120 },
            { "demonic_purge", 70 },
            { "mass_serpent_ward", 110 },
            { "chakram", 8 },
            { "global_silence", 130 },
            { "reincarnation", 180 },
            { "mystic_flare", 60 },
            { "amplify_damage", 5 },
            { "shadow_dance", 50 },
            { "mortimer_kisses", 120 },
            { "assassinate", 20 },
            { "haunt_single", 60 },
            { "nether_strike", 75 },
            { "ball_lightning", 0 },
            { "gods_strength", 110 },
            { "land_mines", 0 },
            { "psionic_trap", 11 },
            { "sunder", 120 },
            { "ravage", 150 },
            { "rearm", 7 },
            { "grow", 0 },
            { "overgrowth", 120 },
            { "battle_trance", 90 },
            { "walrus_punch", 16 },
            { "flesh_golem", 140 },
            { "enrage", 70 },
            { "nether_swap", 46 },
            { "noxious_plague", 100 },
            { "viper_strike", 50 },
            { "summon_familiars", 130 },
            { "astral_step", 0 },
            { "rain_of_chaos", 160 },
            { "time_lapse", 70 },
            { "focusfire", 70 },
            { "winters_curse", 85 },
            { "relocate", 100 },
            { "death_ward", 100 },
            { "thundergods_wrath", 130 },
        };
        public UltimateTimer Timer { get; set; }

        public Ultimate(string name)
        {
            Name = name;
            UltImagePath = ImageManager.MakeImagePathApplicationRelative(ImageManager.GetUltimateImagePath(Name));
            if (_cooldowns.TryGetValue(name, out int cooldownDurationSeconds))
            {
                CooldownDurationSeconds = cooldownDurationSeconds;
            }

            Timer = new UltimateTimer(CooldownDurationSeconds);
        }
    }
}
